<?php

/**
 * @file ding_speedware.module
 */

/**
 * Implements hook_menu().
 */
function ding_speedware_menu(){
  $menu = array(
    'admin/config/services/speedware' => array(
      'title' => 'Speedware',
      'description' => 'Speedware settings',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ding_speedware_admin_form'),
      'access arguments' => array('access administration pages'),
      'file' => 'ding_speedware.service.inc',
    ),
  );

  return $menu;
}

/**
 * Speedware admin form.
 */
function ding_speedware_admin_form() {
  $form = array();
  $service_uri = variable_get('speedware_service_uri', FALSE);

  $form['speedware_service_uri'] = array(
    '#title' => 'Speedware service WSDL URI',
    '#description' => 'Link to WDSL page, e.g. https://www.speedadmin.dk/public/speedadmin.asmx?WSDL',
    '#type' => 'textfield',
    '#default_value' => $service_uri,
  );

  $form['speedware_default_school'] = array(
    '#title' => 'Default school name',
    '#type' => 'select',
    '#options' => array(),
    '#default_value' => variable_get('speedware_default_school', FALSE),
  );

  try {
    _ding_speedware_validate_service_uri($service_uri);
    $form['speedware_default_school']['#options'][] = t('Select');
    foreach(_speedware_get_all_schools() as $school) {
      $form['speedware_default_school']['#options'][$school->SchoolShortName] = $school->SchoolName . ' (' . $school->SchoolShortName . ')';
    }
  }
  catch (RuntimeException $e) {
    $form['speedware_default_school']['#description'] = t('Valid service URI should be set to load list of schools');
  }

  $form['speedware_debug'] = array(
    '#title' => 'Debug mode',
    '#type' => 'checkbox',
    '#default_value' => variable_get('speedware_debug', FALSE),
  );

  return system_settings_form($form);
}

/**
 * Speedware admin form validation.
 */
function ding_speedware_admin_form_validate($form, &$form_state) {
  try {
    _ding_speedware_validate_service_uri($form['speedware_service_uri']['#value']);
  }
  catch (RuntimeException $e) {
    form_set_error('speedware_service_uri', $e->getMessage());
    variable_set('speedware_service_uri', FALSE);
  }
}

/**
 * Validate URI.
 *
 * @param string $uri
 *  WSDL URI.
 * @throws RuntimeException
 */
function _ding_speedware_validate_service_uri($uri) {
  $handle = curl_init($uri);
  curl_setopt($handle,  CURLOPT_RETURNTRANSFER, TRUE);
  $response = curl_exec($handle);
  $httpCode = curl_getinfo($handle, CURLINFO_HTTP_CODE);
  $type = curl_getinfo($handle, CURLINFO_CONTENT_TYPE);
  curl_close($handle);

  if($httpCode == 404 || !stristr($type, 'xml')) {
    throw new RuntimeException(t('The service URI is incorrect'));
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function ding_speedware_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_theme().
 */
function ding_speedware_theme($existing, $type, $theme, $path) {
  // Do not rely on path - it may be unknown to module_invoke_all caller.
  $path = drupal_get_path('module', 'ding_speedware') . '/templates';

  $themes = array(
    'speedware_concerts' => array(
      'path' => $path,
      'template' => 'speedware_concerts',
      'variables' => array(
        'items' => NULL,
      ),
    ),
    'speedware_concerts_pane' => array(
      'path' => $path,
      'template' => 'speedware_concerts_pane',
      'variables' => array(
        'items' => NULL,
      ),
    ),
    'speedware_teachers' => array(
      'path' => $path,
      'template' => 'speedware_teachers',
      'variables' => array(
        'items' => NULL,
      ),
    ),
    'speedware_instruments' => array(
      'path' => $path,
      'template' => 'speedware_instruments',
      'variables' => array(
        'items' => NULL,
      ),
    ),
  );

  return $themes;
}

/**
 * Ctools admin view pane's title.
 */
function ding_speedware_content_type_admin_title() {
  return t('Ding Speedware');
}
