<?php
/**
 * File for the class which returns the class map definition
 * @package Speedware
 * @author Mikaël DELSOL <contact@wsdltophp.com>
 * @version 20130801-01
 * @date 2013-08-06
 */
/**
 * Class which returns the class map definition by the static method SpeedwareClassMap::classMap()
 * @package Speedware
 * @author Mikaël DELSOL <contact@wsdltophp.com>
 * @version 20130801-01
 * @date 2013-08-06
 */
class SpeedwareClassMap
{
	/**
	 * This method returns the array containing the mapping between WSDL structs and generated classes
	 * This array is sent to the SoapClient when calling the WS
	 * @return array
	 */
	final public static function classMap()
	{
		return array (
  'Afdeling' => 'SpeedwareStructAfdeling',
  'Aktivitet' => 'SpeedwareStructAktivitet',
  'AktivitetDetaljer' => 'SpeedwareStructAktivitetDetaljer',
  'ArrayOfAfdeling' => 'SpeedwareStructArrayOfAfdeling',
  'ArrayOfAktivitet' => 'SpeedwareStructArrayOfAktivitet',
  'ArrayOfAktivitetDetaljer' => 'SpeedwareStructArrayOfAktivitetDetaljer',
  'ArrayOfAttribute' => 'SpeedwareStructArrayOfAttribute',
  'ArrayOfBooking' => 'SpeedwareStructArrayOfBooking',
  'ArrayOfBookingAttribute' => 'SpeedwareStructArrayOfBookingAttribute',
  'ArrayOfBookingImage' => 'SpeedwareStructArrayOfBookingImage',
  'ArrayOfBookingPublishingType' => 'SpeedwareStructArrayOfBookingPublishingType',
  'ArrayOfBookingType' => 'SpeedwareStructArrayOfBookingType',
  'ArrayOfEducationOffer' => 'SpeedwareStructArrayOfEducationOffer',
  'ArrayOfImageRessource' => 'SpeedwareStructArrayOfImageRessource',
  'ArrayOfInt' => 'SpeedwareStructArrayOfInt',
  'ArrayOfKategori' => 'SpeedwareStructArrayOfKategori',
  'ArrayOfKoncert' => 'SpeedwareStructArrayOfKoncert',
  'ArrayOfKoncertDetaljer' => 'SpeedwareStructArrayOfKoncertDetaljer',
  'ArrayOfLaerer' => 'SpeedwareStructArrayOfLaerer',
  'ArrayOfLocation' => 'SpeedwareStructArrayOfLocation',
  'ArrayOfLokale' => 'SpeedwareStructArrayOfLokale',
  'ArrayOfRoom' => 'SpeedwareStructArrayOfRoom',
  'ArrayOfSammenspil' => 'SpeedwareStructArrayOfSammenspil',
  'ArrayOfSchool' => 'SpeedwareStructArrayOfSchool',
  'ArrayOfSkole' => 'SpeedwareStructArrayOfSkole',
  'ArrayOfString' => 'SpeedwareStructArrayOfString',
  'ArrayOfStudent' => 'SpeedwareStructArrayOfStudent',
  'ArrayOfSubCategory' => 'SpeedwareStructArrayOfSubCategory',
  'ArrayOfTree' => 'SpeedwareStructArrayOfTree',
  'ArrayOfUnderKategori' => 'SpeedwareStructArrayOfUnderKategori',
  'ArrayOfUndervisningsTilbudUnderkategori' => 'SpeedwareStructArrayOfUndervisningsTilbudUnderkategori',
  'ArrayOfUndervisningstilbud' => 'SpeedwareStructArrayOfUndervisningstilbud',
  'Attribute' => 'SpeedwareStructAttribute',
  'Booking' => 'SpeedwareStructBooking',
  'BookingAttribute' => 'SpeedwareStructBookingAttribute',
  'BookingImage' => 'SpeedwareStructBookingImage',
  'BookingPublishingType' => 'SpeedwareStructBookingPublishingType',
  'BookingType' => 'SpeedwareStructBookingType',
  'EducationOffer' => 'SpeedwareStructEducationOffer',
  'Exists' => 'SpeedwareStructExists',
  'ExistsResponse' => 'SpeedwareStructExistsResponse',
  'GetAfdeling' => 'SpeedwareStructGetAfdeling',
  'GetAfdelingResponse' => 'SpeedwareStructGetAfdelingResponse',
  'GetBookingByType' => 'SpeedwareStructGetBookingByType',
  'GetBookingByTypeAndRoom' => 'SpeedwareStructGetBookingByTypeAndRoom',
  'GetBookingByTypeAndRoomResponse' => 'SpeedwareStructGetBookingByTypeAndRoomResponse',
  'GetBookingByTypeResponse' => 'SpeedwareStructGetBookingByTypeResponse',
  'GetBookingPublishingTypes' => 'SpeedwareStructGetBookingPublishingTypes',
  'GetBookingPublishingTypesResponse' => 'SpeedwareStructGetBookingPublishingTypesResponse',
  'GetBookingTypes' => 'SpeedwareStructGetBookingTypes',
  'GetBookingTypesResponse' => 'SpeedwareStructGetBookingTypesResponse',
  'GetBookingsByTypesAndRooms' => 'SpeedwareStructGetBookingsByTypesAndRooms',
  'GetBookingsByTypesAndRoomsFutureOnly' => 'SpeedwareStructGetBookingsByTypesAndRoomsFutureOnly',
  'GetBookingsByTypesAndRoomsFutureOnlyResponse' => 'SpeedwareStructGetBookingsByTypesAndRoomsFutureOnlyResponse',
  'GetBookingsByTypesAndRoomsFutureOnly_Test' => 'SpeedwareStructGetBookingsByTypesAndRoomsFutureOnly_Test',
  'GetBookingsByTypesAndRoomsFutureOnly_TestResponse' => 'SpeedwareStructGetBookingsByTypesAndRoomsFutureOnly_TestResponse',
  'GetBookingsByTypesAndRoomsResponse' => 'SpeedwareStructGetBookingsByTypesAndRoomsResponse',
  'GetEducationOffer' => 'SpeedwareStructGetEducationOffer',
  'GetEducationOfferResponse' => 'SpeedwareStructGetEducationOfferResponse',
  'GetImage' => 'SpeedwareStructGetImage',
  'GetImageResponse' => 'SpeedwareStructGetImageResponse',
  'GetLocations' => 'SpeedwareStructGetLocations',
  'GetLocationsResponse' => 'SpeedwareStructGetLocationsResponse',
  'GetRooms' => 'SpeedwareStructGetRooms',
  'GetRoomsResponse' => 'SpeedwareStructGetRoomsResponse',
  'GetSchoolList' => 'SpeedwareStructGetSchoolList',
  'GetSchoolListResponse' => 'SpeedwareStructGetSchoolListResponse',
  'GetStudentListByTeacher' => 'SpeedwareStructGetStudentListByTeacher',
  'GetStudentListByTeacherResponse' => 'SpeedwareStructGetStudentListByTeacherResponse',
  'GetTreeList' => 'SpeedwareStructGetTreeList',
  'GetTreeListByTreeTypeID' => 'SpeedwareStructGetTreeListByTreeTypeID',
  'GetTreeListByTreeTypeIDResponse' => 'SpeedwareStructGetTreeListByTreeTypeIDResponse',
  'GetTreeListResponse' => 'SpeedwareStructGetTreeListResponse',
  'GetUndervisningsTilbudUnderkategoriByUTID' => 'SpeedwareStructGetUndervisningsTilbudUnderkategoriByUTID',
  'GetUndervisningsTilbudUnderkategoriByUTIDResponse' => 'SpeedwareStructGetUndervisningsTilbudUnderkategoriByUTIDResponse',
  'GetUndervisningstilbudByTreeID' => 'SpeedwareStructGetUndervisningstilbudByTreeID',
  'GetUndervisningstilbudByTreeIDResponse' => 'SpeedwareStructGetUndervisningstilbudByTreeIDResponse',
  'GetUndervisningstilbudListByKategoriID' => 'SpeedwareStructGetUndervisningstilbudListByKategoriID',
  'GetUndervisningstilbudListByKategoriIDResponse' => 'SpeedwareStructGetUndervisningstilbudListByKategoriIDResponse',
  'HentAktivitetDetaljeListe' => 'SpeedwareStructHentAktivitetDetaljeListe',
  'HentAktivitetDetaljeListeResponse' => 'SpeedwareStructHentAktivitetDetaljeListeResponse',
  'HentAktivitetDetaljer' => 'SpeedwareStructHentAktivitetDetaljer',
  'HentAktivitetDetaljerResponse' => 'SpeedwareStructHentAktivitetDetaljerResponse',
  'HentAktivitetListe' => 'SpeedwareStructHentAktivitetListe',
  'HentAktivitetListeResponse' => 'SpeedwareStructHentAktivitetListeResponse',
  'HentAktivitetsListeSomHTML' => 'SpeedwareStructHentAktivitetsListeSomHTML',
  'HentAktivitetsListeSomHTMLResponse' => 'SpeedwareStructHentAktivitetsListeSomHTMLResponse',
  'HentKoncertDetaljeListe' => 'SpeedwareStructHentKoncertDetaljeListe',
  'HentKoncertDetaljeListeResponse' => 'SpeedwareStructHentKoncertDetaljeListeResponse',
  'HentKoncertDetaljer' => 'SpeedwareStructHentKoncertDetaljer',
  'HentKoncertDetaljerResponse' => 'SpeedwareStructHentKoncertDetaljerResponse',
  'HentKoncertListe' => 'SpeedwareStructHentKoncertListe',
  'HentKoncertListeResponse' => 'SpeedwareStructHentKoncertListeResponse',
  'HentKoncertListeSomHTML' => 'SpeedwareStructHentKoncertListeSomHTML',
  'HentKoncertListeSomHTMLResponse' => 'SpeedwareStructHentKoncertListeSomHTMLResponse',
  'HentLaererList' => 'SpeedwareStructHentLaererList',
  'HentLaererListResponse' => 'SpeedwareStructHentLaererListResponse',
  'HentLokaleListe' => 'SpeedwareStructHentLokaleListe',
  'HentLokaleListeResponse' => 'SpeedwareStructHentLokaleListeResponse',
  'HentSammenspilDetalje' => 'SpeedwareStructHentSammenspilDetalje',
  'HentSammenspilDetaljeResponse' => 'SpeedwareStructHentSammenspilDetaljeResponse',
  'HentSammenspilListe' => 'SpeedwareStructHentSammenspilListe',
  'HentSammenspilListeResponse' => 'SpeedwareStructHentSammenspilListeResponse',
  'HentSkoleList' => 'SpeedwareStructHentSkoleList',
  'HentSkoleListResponse' => 'SpeedwareStructHentSkoleListResponse',
  'HentUndervisningstilbudDetalje' => 'SpeedwareStructHentUndervisningstilbudDetalje',
  'HentUndervisningstilbudDetaljeResponse' => 'SpeedwareStructHentUndervisningstilbudDetaljeResponse',
  'HentUndervisningstilbudListe' => 'SpeedwareStructHentUndervisningstilbudListe',
  'HentUndervisningstilbudListeResponse' => 'SpeedwareStructHentUndervisningstilbudListeResponse',
  'ImageRessource' => 'SpeedwareStructImageRessource',
  'ImageType' => 'SpeedwareEnumImageType',
  'Kategori' => 'SpeedwareStructKategori',
  'Koncert' => 'SpeedwareStructKoncert',
  'KoncertDetaljer' => 'SpeedwareStructKoncertDetaljer',
  'Laerer' => 'SpeedwareStructLaerer',
  'Location' => 'SpeedwareStructLocation',
  'Lokale' => 'SpeedwareStructLokale',
  'Room' => 'SpeedwareStructRoom',
  'Sammenspil' => 'SpeedwareStructSammenspil',
  'School' => 'SpeedwareStructSchool',
  'SelectSubCat' => 'SpeedwareStructSelectSubCat',
  'SelectSubCatResponse' => 'SpeedwareStructSelectSubCatResponse',
  'Skole' => 'SpeedwareStructSkole',
  'Student' => 'SpeedwareStructStudent',
  'SubCategory' => 'SpeedwareStructSubCategory',
  'Tree' => 'SpeedwareStructTree',
  'TreeStructure' => 'SpeedwareStructTreeStructure',
  'UnderKategori' => 'SpeedwareStructUnderKategori',
  'UndervisningsTilbudUnderkategori' => 'SpeedwareStructUndervisningsTilbudUnderkategori',
  'Undervisningstilbud' => 'SpeedwareStructUndervisningstilbud',
);
	}
}
?>